### ISSUE TITLE
Order of open images under OSX (APFS format)

### ISSUE THREAD

**Issue by cleterrier** [ImageScience/NeuronJ#2]
The opening of the next image in a folder using the right arrow shortcut is very useful in NeuronJ. however, for Macs with the newer APFS file system (introduced in Mac OS 10.13), the alphabetical order of files is not respected: images are open in a seemingly random order when using the right arrow shortcut. This is a common problem with the new APFS format, where the content of a folder is not always returned in alphabetical order. Would it be possible to sort the file list inside NeuronJ to correct this behavior?

**Comment by emeijering** [comment]
Thanks for the suggestion. It has been added to the wish list of NeuronJ. But the next release has not been scheduled yet, so it may take a while before this gets implemented.
